#!/usr/bin/perl -w

use strict;

my $receiver_pid = fork;

if ( $receiver_pid < 0 ) {
  die qq{$!};
} elsif ( $receiver_pid == 0 ) {
  # child
  exec q{/home/verus/cs244-verus/cubic/server.py 5050} or die qq{$!};
}

# run the sender inside a linkshell and a delayshell
my @command = qw{mm-delay 20 mm-link UPLINK DOWNLINK --once --downlink-queue=droptail --downlink-queue-args=bytes=120000 --uplink-queue=droptail --uplink-queue-args=bytes=120000 --meter-uplink --meter-uplink-delay --uplink-log=/home/verus/cs244-verus/logs/tmobile_drive_cubic -- sh -c};

push @command, q{/home/verus/cs244-verus/cubic/client.py 5050 1};

die unless $command[ 3 ] eq "UPLINK";
$command[ 3 ] = qq{/home/verus/cs244-verus/traces/TMobile-LTE-driving.up};

die unless $command[ 4 ] eq "DOWNLINK";
$command[ 4 ] = qq{/home/verus/cs244-verus/traces/TMobile-LTE-driving.up};

system @command;

# kill the receiver
kill 'INT', $receiver_pid;

print "\n";

# analyze performance locally
system q{mm-throughput-graph 500 /home/verus/cs244-verus/logs/tmobile_drive_cubic > /dev/null};

print "\n";
